version: '3'
services:
  nominatim:
    image: mediagis/nominatim:4.1
    ports:
      - 8080:8080
    environment:
      - PBF_URL=https://download.geofabrik.de/south-america/brazil-latest.osm.pbf
      - REPLICATION_URL=https://download.geofabrik.de/south-america/brazil-updates/